[package]
name = "keba_home_api"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
